### ISSUE TITLE
国服数据库会战数据解析崩溃

### ISSUE THREAD

**Issue by Sun45** [MalitsPlus/ShizuruNotes#70]
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.github.malitsplus.shizurunotes.debug, PID: 3041
    java.time.format.DateTimeParseException: Text '2023/1/26 5:00:00' could not be parsed at index 5
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
        at java.time.LocalDateTime.parse(LocalDateTime.java:486)
        at com.github.malitsplus.shizurunotes.db.RawClanBattlePeriod.transToClanBattlePeriod(RawClanBattlePeriod.java:18)
        at com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:32)
        at com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelClanBattle$loadData$1.invoke(SharedViewModelClanBattle.kt:29)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```
把RawClanBattlePeriod里改下我这里测试能正常运行，也不会影响日服数据
`DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy/M/dd H:mm:ss");`

**Comment by MalitsPlus** [comment]
感谢测试，方便提个PR吗

**Comment by Sun45** [comment]
https://github.com/MalitsPlus/ShizuruNotes/pull/71

**Comment by Sun45** [comment]
国服数据库活动数据解析也崩溃了，一样的问题
https://github.com/MalitsPlus/ShizuruNotes/pull/72
提交了，大佬有空看下

**Comment by MalitsPlus** [comment]
> 国服数据库活动数据解析也崩溃了，一样的问题 #72 提交了，大佬有空看下

草，乱打牌啊国服（

**Comment by Sun45** [comment]
`E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.github.malitsplus.shizurunotes.debug, PID: 21716
    java.time.format.DateTimeParseException: Text '2023/3/8 12:00:00' could not be parsed at index 7
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
        at java.time.LocalDateTime.parse(LocalDateTime.java:486)
        at com.github.malitsplus.shizurunotes.db.MasterHatsune.getHatsune(MasterHatsune.kt:17)
        at com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelHatsune$loadData$1.invoke(SharedViewModelHatsune.kt:17)
        at com.github.malitsplus.shizurunotes.ui.shared.SharedViewModelHatsune$loadData$1.invoke(SharedViewModelHatsune.kt:16)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
I/Process: Sending signal. PID: 21716 SIG: 9
`
没想到不仅”月“能出问题，“日”也出问题了，我顺便把“分”和“秒”改了下，活动日期和会战日期两边的解析，测试没啥问题，麻烦再看下，还好不会出现‘2023/3/8 12::’
https://github.com/MalitsPlus/ShizuruNotes/pull/76
